server:
  port: 8081
eureka:
  client:
    serviceUrl: #注册中心的地址
      defaultZone: http://127.0.0.1:8080/eureka/
spring:
  application:
    name: User
  datasource:
      url: jdbc:mysql://192.168.32.128:3306/wanengod?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  config: classpath:logback.xml
mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.xinqiu.entity

