server:
  port: 8081
eureka:
  client:
    serviceUrl: #注册中心的地址
      defaultZone: http://127.0.0.1:8080/eureka/
spring:
  application:
    name: User
  datasource:
      url: jdbc:mysql://192.168.32.128:3306/wanengod?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&AllowPublicKeyRetrieval=True
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
logging:
  config: classpath:logback.xml
mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.xinqiu.entity

